name: nlp-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.24.*
  - pandas=2.0.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - scikit-learn=1.3.*
  - jupyter
  - notebook
  - ipykernel
  - pip
  - pip:
    - nbformat
