name: nlp-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21,<2.0
  - pandas>=1.5,<3.0
  - matplotlib>=3.5,<4.0
  - seaborn>=0.11,<1.0
  - scikit-learn>=1.1,<2.0
  - jupyter
  - notebook
  - ipykernel
  - jupyterlab
  - ipywidgets
  - widgetsnbextension
  - pip
  - pip:
    - nbformat